
version: '3.8'

services:
  citaplanner-db:
    image: postgres:15-alpine
    container_name: citaplanner-db
    restart: always
    environment:
      POSTGRES_USER: citaplanner_admin
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: citaplanner_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - citaplanner_internal

  citaplanner-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: citaplanner-app
    restart: always
    depends_on:
      - citaplanner-db
    environment:
      DATABASE_URL: postgresql://citaplanner_admin:${DATABASE_PASSWORD}@citaplanner-db:5432/citaplanner_prod?schema=public
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${DOMAIN_URL}
      API_KEY: ${API_KEY}
    volumes:
      - uploads_data:/app/uploads
    networks:
      - citaplanner_internal

volumes:
  postgres_data:
  uploads_data:

networks:
  citaplanner_internal:
    driver: bridge
